apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oq-engine
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oq-engine
    spec:
      tolerations: [{"key": "oneconcern.com/seismic","operator": "Equal","value": "seismic-mitigation"}]
      nodeSelector: {"kubernetes.io/role":"seismic-mitigation"}
      containers:
        - name: oq-engine
          image: gcr.io/onec-co/oq:latest
          volumeMounts:
            - mountPath: /mnt/shared
              name: shared-vol
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: pvc1
            readOnly: false
