version: '2'
services:
  # Engine is not actually executed and is
  # exposed only to make sure it is built via
  # docker-compose build
  # engine:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.engine
  #   image: openquake/engine
  #   command: '-c true'
  master:
    build:
      context: .
      dockerfile: zmq/Dockerfile.master
    image: openquake/engine-master-zmq
    # Uncomment to enable auth in WebUI/API
    # environment:
    #   - LOCKDOWN=true
    volumes:
      - oqdata:/home/openquake/oqdata
    # Uncomment to expose demos inside the container
    #   - ../demos:/home/openquake/demos:ro
    # Uncomment to use a local copy of the oq-engine
    #   - ../openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    # Uncomment to use a custom openquake.cfg
    #   - ./path/to/openquake.cfg:/etc/openquake/openquake.cfg
    networks:
      - cluster
    ports:
      - 8800:8800
  worker:
    build:
      context: .
      dockerfile: zmq/Dockerfile.worker
    image: openquake/engine-worker-zmq
    volumes:
      - oqdata:/home/openquake/oqdata:ro
    # Uncomment to use a local copy of the oq-engine
    #   - ../openquake:/opt/openquake/lib/python3.6/site-packages/openquake
    # Uncomment to use a custom openquake.cfg
    #   - ./path/to/openquake.cfg:/etc/openquake/openquake.cfg
    networks:
      - cluster
    depends_on:
      - master

# When running on multiple host the volume must be shared between every node
# see the 'oqdata-nfs' example below
volumes:
  oqdata:
  # oqdata-nfs:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: nfsvers=4,addr=nfs-server,rw
  #     device: ":/oqdata"

networks:
  cluster:
